FROM node:22.17.0-alpine3.21 AS base
WORKDIR /app

# deps
FROM base AS deps
COPY package*.json ./
RUN npm ci

# build
FROM base AS build
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_API_URL
ARG API_PROXY_TARGET

ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV API_PROXY_TARGET=$API_PROXY_TARGET
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# runner
FROM node:22.17.0-alpine3.21 AS runner
WORKDIR /app
ENV NODE_ENV=production


COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

CMD ["node", "server.js"]
